version: "3.8"

services:
  backend:
    container_name: chatfusion_backend
    build: .
    restart: always
    ports:
      - "5550:5550"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      # Within the shared network, MySQL is reachable by its container name on its internal port (3306)
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
    command: sh -c "npm start"

networks:
  whatsapp_network:
    external: true
